"""Small, testable presentation helpers for the Antardhi Streamlit app."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Mapping

import pandas as pd


SOURCE_LABELS: dict[str, str] = {
    "upi": "UPI cash-flow history", "gst": "GST filings", "utility": "Utility payments",
    "telecom": "Telecom recharges", "ecommerce": "E-commerce activity", "mobility": "Mobility activity",
}
PERSONA_SOURCES: dict[str, tuple[str, ...]] = {
    "Small Merchant": ("upi", "gst", "utility", "ecommerce"),
    "Gig Worker": ("upi", "telecom", "mobility"),
    "First-time Borrower": ("upi", "utility", "telecom"),
    "Informal/Rural Worker": ("upi", "utility", "telecom"),
}

CUSTOMER_SCHEMA: tuple[str, ...] = (
    "customer_id", "persona", "upi_monthly_inflow_avg", "upi_inflow_volatility",
    "upi_active_days_per_month", "gst_monthly_turnover", "gst_filing_consistency",
    "utility_payment_regularity", "utility_avg_delay_days", "telecom_recharge_frequency",
    "telecom_recharge_consistency", "ecommerce_txn_frequency", "ecommerce_return_rate",
    "mobility_active_days", "mobility_distance_trend", "existing_bureau_flag",
    "existing_bureau_score_partial", "months_of_data_available", "num_sources_available",
    "default_label",
)


def source_connection_status(persona: str, consents: Mapping[str, bool]) -> list[dict[str, Any]]:
    """Return source availability and explicit-consent status for a persona."""
    available_sources = set(PERSONA_SOURCES.get(persona, ()))
    return [{"key": key, "source": label, "available_for_persona": key in available_sources,
             "consented": bool(consents.get(key, False)),
             "connected": key in available_sources and bool(consents.get(key, False))}
            for key, label in SOURCE_LABELS.items()]


def coverage_percent(statuses: list[Mapping[str, Any]]) -> int:
    """Calculate consented coverage among sources applicable to a persona."""
    applicable = [item for item in statuses if item["available_for_persona"]]
    if not applicable:
        return 0
    return round(100 * sum(bool(item["connected"]) for item in applicable) / len(applicable))


def load_demo_customers(dataset_path: Path) -> pd.DataFrame:
    """Load and validate synthetic customer records used by the demo.

    Args:
        dataset_path: CSV file generated by the synthetic-data module.

    Returns:
        Customer records in the exact Section 5.1 schema order.

    Raises:
        ValueError: If the source file does not contain the required schema.
    """
    customers = pd.read_csv(dataset_path)
    missing = [column for column in CUSTOMER_SCHEMA if column not in customers.columns]
    if missing:
        raise ValueError(f"Synthetic dataset is missing required columns: {', '.join(missing)}")
    return customers.loc[:, CUSTOMER_SCHEMA].copy()


def fingerprint_indicators(customer_row: pd.Series) -> dict[str, float | None]:
    """Derive supporting source-signal indicators from one real customer row.

    These are not model-provided Capacity, Stability, or Discipline components.
    They are transparent displays of raw-data signals for the app fingerprint.

    Args:
        customer_row: A Section 5.1 customer record.

    Returns:
        Available indicators scaled from 0 to 100; unavailable signals are None.
    """
    active_days = pd.to_numeric(customer_row.get("upi_active_days_per_month"), errors="coerce")
    volatility = pd.to_numeric(customer_row.get("upi_inflow_volatility"), errors="coerce")
    payment_values = [pd.to_numeric(customer_row.get(column), errors="coerce")
                      for column in ("utility_payment_regularity", "telecom_recharge_consistency")]
    available_payments = [value for value in payment_values if pd.notna(value)]
    return {
        "Capacity": None if pd.isna(active_days) else float(max(0, min(100, active_days / 30 * 100))),
        "Stability": None if pd.isna(volatility) else float(max(0, min(100, (1 - volatility) * 100))),
        "Discipline": None if not available_payments else float(sum(available_payments) / len(available_payments) * 100),
    }


def risk_tier_label(tier: str) -> str:
    """Return a short user-facing risk-tier label."""
    labels = {"Low": "Low risk", "Medium": "Medium risk", "High": "High risk",
              "Low Risk": "Low risk", "Medium Risk": "Medium risk", "High Risk": "High risk"}
    return labels.get(tier, tier or "Risk tier unavailable")
